/**
 * LibrePay Node — centralized environment access (server-side).
 *
 * Single-merchant, self-hosted edition: the merchant IS the operator.
 * Every value degrades gracefully so `bun run dev` works out of the box,
 * but the payment rail stays DARK until a wallet is configured.
 */

const bool = (v: string | undefined) => v === "true" || v === "1";

export const env = {
  /** Public base URL of this node (https://pay.example.com) — no trailing slash */
  get BASE_URL() {
    return (process.env.LP_BASE_URL ?? "").replace(/\/+$/, "");
  },
  /** Human store name shown on checkout */
  get STORE_NAME() {
    return process.env.LP_STORE_NAME ?? "LibrePay Node";
  },
  /** #rrggbb brand color on checkout */
  get BRAND_COLOR() {
    return process.env.LP_BRAND_COLOR ?? "#f7931a";
  },

  // ── wallet (choose ONE rail; both can coexist) ──
  /** BIP47 payment code (PM8T…) → per-invoice stealth addresses */
  get PAYMENT_CODE() {
    return process.env.LP_PAYMENT_CODE ?? null;
  },
  /** zpub (BIP84) or xpub → deterministic watch-only addresses m/0/{index} */
  get XPUB() {
    return process.env.LP_ZPUB ?? process.env.LP_XPUB ?? null;
  },
  get CONFIRMATIONS_REQUIRED() {
    const n = Number(process.env.LP_CONFIRMATIONS_REQUIRED ?? 2);
    return Number.isFinite(n) && n >= 1 ? Math.min(Math.floor(n), 6) : 2;
  },
  get INVOICE_EXPIRY_MINUTES() {
    const n = Number(process.env.LP_INVOICE_EXPIRY_MINUTES ?? 15);
    return Number.isFinite(n) && n >= 5 ? Math.min(Math.floor(n), 120) : 15;
  },

  // ── API access ──
  /** Merchant API key, format lp_live_<48 hex>. Generated by `bun run setup`. */
  get API_KEY() {
    return process.env.LP_API_KEY ?? null;
  },

  // ── webhooks ──
  /** Comma-separated https URLs to receive signed events */
  get WEBHOOK_URLS() {
    return (process.env.LP_WEBHOOK_URLS ?? "")
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);
  },
  /** Secret(s) signing the raw body: one value, or comma-matched to URLs */
  get WEBHOOK_SECRETS() {
    return (process.env.LP_WEBHOOK_SECRETS ?? "")
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);
  },
  /**
   * Operator escape hatch for LOCAL integration tests only: allows loopback
   * http:// webhook endpoints (127.0.0.1/localhost/::1). Never enable on a
   * server that routes webhooks to third-party-controlled URLs. Default false.
   */
  get ALLOW_LOOPBACK_WEBHOOKS() {
    return bool(process.env.LP_ALLOW_LOOPBACK_WEBHOOKS);
  },

  // ── Lightning (phoenixd on the same box) ──
  get LIGHTNING_URL() {
    return process.env.LP_LIGHTNING_URL ?? null;
  },
  /** phoenixd http-password — plaintext in .env; the node never spends, only mints */
  get LIGHTNING_PASSWORD() {
    return process.env.LP_LIGHTNING_PASSWORD ?? null;
  },

  // ── chain outage alarm (self-monitoring) ──
  /** Signed JSON POST target for system.esplora_down / _up / _stalled alarms */
  get ALARM_WEBHOOK_URL() {
    return process.env.LP_ALARM_WEBHOOK_URL ?? null;
  },
  /** Signature secret for the alarm POST (falls back to first WEBHOOK_SECRETS entry) */
  get ALARM_WEBHOOK_SECRET() {
    return process.env.LP_ALARM_WEBHOOK_SECRET ?? null;
  },
  /** Consecutive chain-API failures before the provider is declared DOWN */
  get ESPLORA_FAIL_THRESHOLD() {
    const n = Number(process.env.LP_ESPLORA_FAIL_THRESHOLD ?? 3);
    return Number.isFinite(n) && n >= 1 ? Math.min(Math.floor(n), 20) : 3;
  },
  /** Minutes without a tip advance before system.esplora_stalled fires */
  get TIP_STALL_MINUTES() {
    const n = Number(process.env.LP_TIP_STALL_MINUTES ?? 90);
    return Number.isFinite(n) && n >= 10 ? Math.floor(n) : 90;
  },

  // ── infra ──
  get ESPLORA_API() {
    return process.env.ESPLORA_API ?? "https://mempool.space/api";
  },
  get DATABASE_URL() {
    return process.env.DATABASE_URL ?? "file:./data/node.db";
  },
  /** App secret for encrypting nothing-at-rest today, HKDF future use */
  get APP_SECRET() {
    return process.env.LP_APP_SECRET ?? null;
  },
  /** Manual cron trigger guard (systemd timer / external scheduler) */
  get CRON_SECRET() {
    return process.env.LP_CRON_SECRET ?? null;
  },
  /** Embedded scheduler period (ms). 0 disables the in-process loop */
  get CRON_INTERVAL_MS() {
    const n = Number(process.env.LP_CRON_INTERVAL_MS ?? 30_000);
    return Number.isFinite(n) && n >= 5_000 ? n : 30_000;
  },
  /** Test mode: POST /api/dev/simulate-payment can settle invoices. NEVER on real money */
  get SIMULATE() {
    return bool(process.env.LP_SIMULATE);
  },
  get NODE_ENV() {
    return process.env.NODE_ENV ?? "development";
  },
};

/** True when at least one on-chain wallet rail is configured. */
export function walletConfigured(): boolean {
  return !!(env.PAYMENT_CODE || env.XPUB);
}
